# Generated by Django 4.1.7 on 2023-03-03 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=255)),
                ('image', models.ImageField(default='../imresizer-1677838586928_dfojm5', upload_to='images/')),
                ('content', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['service'],
            },
        ),
    ]
