# Generated by Django 4.1.7 on 2023-03-06 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='ends_at',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='starts_at',
            field=models.TimeField(),
        ),
    ]
